CREATE TABLE bj_life.service_category (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_class_code CHAR(3) NOT NULL UNIQUE,
    service_class_name VARCHAR(50) NOT NULL UNIQUE
);